---
- name: Downloading packer
  get_url:
      url: https://releases.hashicorp.com/packer/1.3.5/packer_1.3.5_linux_amd64.zip
      dest: .

- name: Unarchive packer
  unarchive:
      src: packer_1.3.5_linux_amd64.zip
      dest: /usr/local

- name: Create link to packer
  file:
      src: /usr/local/packer
      dest: /usr/local/bin/packer.io
      state: link

- name: Install pip
  yum:
      name: python-pip
      state: present

- name: installing Docker
  pip:
      name: docker-py

- name: Install Docker Packages
  yum:
      name: "{{ item }}"
      state: present
  loop: "{{ docker_packages }}"

- name: enable and start Docker
  systemd:
      name: docker
      state: started
      enabled: yes

- name: Add the current user to docker group
  user:
      name: "{{ ansible_user }}"
      groups: docker
      append: yes

