---
- name: Run using a project directory
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    - volume_path: /home/ansibleuser1/project-flask-react/testdriven-app/users-service
  tasks:
    - docker_service:
        project_name: flask
        definition:
          version: '3.3'
          services:
            flaskapp:
              image: uav2608/flask:0.0.2
              volumes:
                - '{{volume_path}}:/usr/src/app'
              ports:
                - "5001:5000"
      register: output
    - debug:
        var: output
    - assert:
        that:
          - "flaskapp.flask_flaskapp_1.state.running"
