---
- name: Create static IP for Centos
  template:
    src: "static_ip.j2"
    dest: /etc/sysconfig/network-scripts/ifcfg-{{ interface_device_name }}
    owner: root
    group: root
    mode: 0644
  notify: Reboot network
  when: ansible_os_family == 'RedHat' 

- name: Create static IP for Debian
  template:
    src: "static_ip.j2"
    dest: "/etc/network/interfaces"
    owner: root
    group: root
    mode: 0644
  notify: Reboot networking
  when: ansible_os_family == 'Debian' 

- name: Enable the "network" service
  service:
    name: network
    enabled: true
  check_mode: yes
  ignore_errors: true
  when: ansible_os_family == 'RedHat'

- name: Enable the "networking" service
  service:
    name: networking
    enabled: true
  check_mode: yes
  ignore_errors: true
  when: ansible_os_family == 'Debian'

- debug:
    msg: "{{ interface_device_name }}"

- debug:
    msg: "{{ static_ip_addr }}"
