---
# Restart interfaces to load new configuration

- name: Create a restart script
  template:
    src: restartscript.j2
    dest: /etc/network/restart.sh
    mode: 0755

# Execute configuration change

- name: Execute Network Restart
  shell: bash /etc/network/restart.sh | true

- name: Cleanup Network Restart script
  file:
    path: /etc/network/restart.sh
    state: absent

