---

- block:
  - name: Make sure to have Wheel group
    group:
      name: wheel
      state: present

  - name: Add user to Wheel group
    user:
      name: "{{ ansible_user }}"
      groups: wheel

  - name: Update sudoer file
    lineinfile:
      path: /etc/sudoers
      state: present
      regexp: '^%wheel\s'
      line: '%wheel ALL=(ALL) NOPASSWD: ALL'
      validate: '/usr/sbin/visudo -cf %s'

  when: ansible_os_family == 'RedHat'


- block:

  - name: Make sure to have Sudo group
    group:
      name: sudo
      state: present

  - name: Add user to Sudo group
    user:
      name: "{{ ansible_user }}"
      groups: sudo

  - name: Update sudoer file
    lineinfile:
      path: /etc/sudoers
      state: present
      regexp: '^%sudo\s'
      line: '%sudo ALL=(ALL) NOPASSWD: ALL'
      validate: '/usr/sbin/visudo -cf %s'

  when: ansible_os_family == 'Debian'


- name: Create a 2048-bit SSH key for user (ansible_user)
  user:
      name: "{{ ansible_user }}"
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_file: .ssh/id_rsa

- name: create a .ssh directory if it doesn't exist
  file:
      path:  /home/{{ ansible_user }}/.ssh
      state: directory
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
      mode: 0700

- name: create file
  file:
      path: /home/{{ ansible_user }}/.ssh/authorized_keys
      state: touch
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
      mode: 0644

- name: Copy authorized_keys
  lineinfile:
      path: /home/{{ ansible_user }}/.ssh/authorized_keys
      state: present
      line: "{{ auth_key_initial }}"

