---
- hosts: localhost
  connection: local
  become: yes
  vars:
    desired_state: present
  tasks:
    - name: deploy Flask container
#      docker_network:
#        name: web_dev
#      docker_volume:
#        name: dev_app
      docker_service:
        project_name: flask
        state: "{{ desired_state }}"
        build: yes
        definition:
          version: "3.3"
          networks: 
            web_dev:
          services:
            web_dev:
              image: uav2608.flask.v1:0.0.3
              ports:
                - "4000:4000"
              volumes:
                - ".:/app"
              environment:
                ENV: development
                PORT: 4000
                DB: mongodb://mongodb:27017/todoDev
      register: output    
    - debug: 
        var: 
          output
#    - assert:
#        that:
#          - "web_dev.flask_web_dev_1.state.running"
#      when: desired_state == "present"


