---
- block:

  - name: Install Packages
    yum:
      name: "{{ item }}"
      state: present
    loop: "{{ vagrant_packages }}"

  - name: installing Vagrant
    yum:
      name: https://releases.hashicorp.com/vagrant/1.9.6/vagrant_1.9.6_x86_64.rpm
      state: present

  when: ansible_os_family == "RedHat"


- block:

  - name: Install Packages
    apt:
      name: "{{ item }}"
      state: present
    loop: "{{ vagrant_packages }}"

  - name: installing Vagrant
    apt:
      name: https://releases.hashicorp.com/vagrant/1.9.6/vagrant_1.9.6_x86_64.rpm
      state: present

  when: ansible_os_family == "Debian"


- name: enable and start libvirtd
  systemd:
      name: libvirtd
      state: started
      enabled: yes

- name: Add the current user to libvirt group
  user:
      name: "{{ ansible_user }}"
      groups: libvirt
      append: yes

- name: installing vagrant-libvirt plugin
  become: no
  shell: vagrant plugin install vagrant-libvirt

