---
- hosts: 127.0.0.1
  connection: local
  gather_facts: yes
  become: true
  become_method: su
  become_user: root
  roles:
    - firstsetup


- hosts: 127.0.0.1
  connection: local
  gather_facts: yes
  become: true
  become_method: su
  become_user: root
  vars:
    linux_desktop: xfce
  vars_files:
    - ~/firstSetup/roles/nextstep/vars/main.yaml
    - ~/firstSetup/roles/packer_docker/vars/main.yaml
#    - ~/firstSetup/roles/vboxguest/vars/main.yml
    - ~/firstSetup/roles/vagrant_only/vars/main.yaml

  roles:
    - nextstep
    - packer_docker
    - linux_desktop
    - vagrant_only

#    - vboxguest
#    - vagrant_only
#    - role: PeterMosmans.virtualbox-guest 
#    - role: ruzickap.vmwaretools
#      when: ansible_virtualization_type == "VMware"

