---
- hosts: 127.0.0.1
  connection: local
  gather_facts: yes
  become: true
  become_method: su
  become_user: root
  roles:
    - firstsetup

- hosts: 127.0.0.1
  connection: local
  gather_facts: yes
  become: true
  vars:
    linux_desktop: xfce

  roles:
    - nextstep
    - packer
    - docker
    - pip
    - mynetwork
    - linux_desktop
    - vagrant
    - kvm   

#    - vb
#    - vboxguest
#    - vagrant_only
#    - role: PeterMosmans.virtualbox-guest 
#    - role: ruzickap.vmwaretools
#      when: ansible_virtualization_type == "VMware"

