---
language: ruby
dist: trusty
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libvirt-dev
  - gem update --system
  - gem install bundler
install: bundle install
script: bundle exec rspec --color --format documentation
notifications:
  email: false
rvm:
  - 2.2.5
  - 2.3.3
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  matrix:
    - VAGRANT_VERSION=v2.0.1
matrix:
  allow_failures:
    - env: VAGRANT_VERSION=master
      rvm: 2.3.3
